name: Cypress Tests
on: 
  push:
    branches:
      - "jest-testing"
      - "develop"
jobs:
  cypress-run:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          node: [14]
      steps:
        - uses: actions/checkout@v1
        - name: Setup Node
          uses: actions/setup-node@v1
          with:
            node-version: ${{ matrix.node }}
        - uses: actions/cache@v1
          id: cache
          with:
            path: |
              ~/.cache/Cypress
              node_modules
            key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}  
        - name: Yarn Install
          run: |
            yarn install
        - name: Run Jest Logic tests
          run: |
            yarn logic-test



        
        
